### ISSUE TITLE
Headless Crash

### ISSUE THREAD

**Issue by gshort** [TerraMap/windows#10]
Couldn't find any documentation on headless mode, assumed it was via TerraMapCmd.exe, got the following:

`
C:\Users\...snipped...>TerraMap\TerraMapCmd.exe
Reading static data...
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Jason\source\Terraria\Terraria.Localization\Content.en-US.Items.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at TerraMap.Program.Main(String[] args) in C:\Users\Jason\source\terramap\windows\Console\Program.cs:line 43
`

Seems to be looking for some stuff from the author's own environment?

Thanks, love this thing!

**Comment by jasoncoon** [comment]
I honestly hadn't even tested the command line renderer lately.  :)

Should be fixed now: https://terramap.github.io/windows

**Comment by gshort** [comment]
Holy smokes, that was fast. Thanks!
