### ISSUE TITLE
Exception Encountered : Object reference not set to an instane of an object.

### ISSUE THREAD

**Issue by Entropii-dev** [TerraMap/windows#14]
It's probably the wrong place to report this. Anyway here's the issue :

System.NullReferenceException: Object reference not set to an instance of an object.
   at TerraMap.MainWindow.GetCloudPaths()
   at TerraMap.MainWindow.LoadWorldFiles()
   at TerraMap.MainWindow.OnWorldsDropDownOpened(Object sender, EventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.OnIsSubmenuOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.MenuItem.OpenMenu()
   at System.Windows.Controls.MenuItem.<SetTimerToOpenHierarchy>b__189_0(Object sender, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Version: 1.4.5.36576

**Comment by jasoncoon** [comment]
This is actually the perfect place to report this, I'll get it fixed, thanks!

**Comment by jasoncoon** [comment]
I think I have this fixed, will be in the next release, hopefully later today.

**Comment by jasoncoon** [comment]
OK, try again with TerraMap v1.4.6?  https://terramap.github.io/windows

**Comment by Entropii-dev** [comment]
Yep, it's working now :)
