### ISSUE TITLE
I wanted to load in modded world and this problem happened.

### ISSUE THREAD

**Issue by IdunnoManSeemsKindagAyTOme** [TerraMap/windows#33]
System.Exception: World file tiles list start is not where it's expected to be. Expected: 2813 Actual: 11011382
   w TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) w C:\Users\Jason\source\terramap\windows\Data\World.cs:wiersz 460
   w TerraMap.Data.World.Read(String filename) w C:\Users\Jason\source\terramap\windows\Data\World.cs:wiersz 435
   w TerraMap.Data.World.<>c__DisplayClass378_0.<ReadAsync>b__0() w C:\Users\Jason\source\terramap\windows\Data\World.cs:wiersz 397
   w System.Threading.Tasks.Task.Execute()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w TerraMap.MainWindow.<Open>d__24.MoveNext() w C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:wiersz 308
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w TerraMap.MainWindow.<Open>d__23.MoveNext() w C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:wiersz 275
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w TerraMap.MainWindow.<OnSelectedWorldFileChanged>d__61.MoveNext() w C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:wiersz 1266
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Version: 1.4.10.20882

**Comment by jasoncoon** [comment]
Try again with the latest release v1.4.11? https://terramap.github.io/windows.html

**Comment by MartinNiederl** [comment]
Same Problem here:

System.Exception: World file tiles list start is not where it's expected to be. Expected: 2816 Actual: 1654
   at TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 463
   at TerraMap.Data.World.Read(String filename) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 438
   at TerraMap.Data.World.<>c__DisplayClass382_0.<ReadAsync>b__0() in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 400
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__24.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__23.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<OnSelectedWorldFileChanged>d__61.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 1266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Version: 1.4.11.28073

**Comment by MartinNiederl** [comment]
@Lyohzeed what do you mean with latest 1.3.5 release? 1.4.11... is after 1.3.5

**Comment by Lyohzeed** [comment]
Which version of tmodloader are you using? Beta for terraria 1.4 or terraria 1.3?
