### ISSUE TITLE
Can no longer load maps as of Terraria 1.4.2.3

### ISSUE THREAD

**Issue by dxgldotorg** [TerraMap/windows#34]
Upon attempting to load a world that has been modified in 1.4.2.3 the following error is given:

System.Exception: World file tiles list start is not where it's expected to be. Expected: 3294 Actual: 1947
   at TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 460
   at TerraMap.Data.World.Read(String filename) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 435
   at TerraMap.Data.World.<>c__DisplayClass378_0.<ReadAsync>b__0() in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 397
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__24.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__23.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<OnSelectedWorldFileChanged>d__61.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 1266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Version: 1.4.10.20882

Attached is a world saved by Terraria 1.4.2.3.

[Zealous_Limbo_of_Cheats.wld.zip](https://github.com/TerraMap/windows/files/6489995/Zealous_Limbo_of_Cheats.wld.zip)

**Comment by jasoncoon** [comment]
Thank you for the report! I'll try to get it updated soon.
