### ISSUE TITLE
1.4.4 world is still not loading correctly

### ISSUE THREAD

**Issue by MimiaMia** [TerraMap/windows#44]
I posted earlier about this issue and I apologize for not responding sooner.  The map is still unable to load (though the viewer itself is not crashing), and the crazy things it is doing to the browser version showed it managed to get worse.  The map loads normally however in Terraria.  It's possible it's an issue with new items but the way it's screwing up seems a little odd.
![Bugged World](https://user-images.githubusercontent.com/114980616/195427113-6e08d4ef-b3ed-4501-9711-837cd318460e.png)

I've since finished my playthrough so it's not disrupting me that this world can't really be loaded, but the issue is ongoing none the less, whatever might be causing it.  Sadly the latest update did not seem to fix this particular world.  I could try additional worlds to see if they have similar problems and confirm it's indeed an issue with items?  I do have shimmered npcs and I used illuminant paint as well.  The only other thing I can imagine is that I was using mannequins and I added more.  I don't mind sharing a copy of the world if it might help you narrow down the issue.

This is the exception error that occurs when I try to load the map on the windows program:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TerraMap.Data.World.ReadTilesVersion2(BinaryReader reader, Boolean[] importance) in C:\Users\~\source\terramap\windows\Data\World.cs:line 1089
   at TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) in C:\Users\~\source\terramap\windows\Data\World.cs:line 483
   at TerraMap.Data.World.Read(String filename) in C:\Users\~\source\terramap\windows\Data\World.cs:line 456
   at TerraMap.Data.World.<>c__DisplayClass406_0.<ReadAsync>b__0() in C:\Users\~\source\terramap\windows\Data\World.cs:line 418
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__24.MoveNext() in C:\Users\~\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 308
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__23.MoveNext() in C:\Users\~\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 275
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<OnSelectedWorldFileChanged>d__61.MoveNext() in C:\Users\~\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 1266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Version: 1.4.15.16157

**Comment by fiziali** [comment]
I'm quite positive that illuminant paint is the culprit. I have this problem too on two areas where I used the paint. I got it fixed on one area once I got the paint removed but not on the other. Probably because I missed a block. Not easy to pinpoint where did I apply the paint on this second area

**Comment by fiziali** [comment]
Just painted a random stone block on a random area with illuminant paint, and as a result that area started to distort. Fixed the area again by removing the paint

**Comment by MimiaMia** [comment]
I tried putting illuminant paint on wooden blocks on a map to test this problem but it had no distortion.  You said you put it on stone--did you by any chance paint grey stone bricks?  That is what I painted with them, as well as stone brick platforms and background walls.

All of this said the issue is much more profound in this version, or it is much more profound now because I did something on the map.  I can only guess at what might be causing problems but the distortion is much worse than when I posted this issue a week ago.

**Comment by fiziali** [comment]
I tried it on just a stone block you would find naturally undeground. 

Now I tried the paint on a wooden bench and it caused no problem as well. Then I tried painting a grey stone brick and yes it caused distortion. Also on torches, those too cause distortions

**Comment by MimiaMia** [comment]
I removed the illuminant paint in my world and it loads completely normally now, even on the Windows program.  So I can confirm without any question that the problem causing the distortion was illuminant paint, probably on specific blocks (it seems like grey stone bricks are at least one culprit).

**Comment by jasoncoon** [comment]
Thanks for all the info! I hope to have a chance to work on this soon. I haven't had a chance to play lately, and don't have any illuminant paint. I usually use `Builder's Workshop` maps to test with, but I haven't been able to find one updated with the latest 1.4.4 content.

Any chance you could send me a link to download a map with illuminant paint?

**Comment by bonanooo** [comment]
> 

1.4.3 version of Builder's Workshop should have illuminant paint as all of them got converted into "Illuminant Coating" in 1.4.4.

**Comment by jasoncoon** [comment]
OK, this shoudld be fixed now: https://terramap.github.io/windows.html

Let me know if you still have problems, or find any new issues, thanks!
