### ISSUE TITLE
Index out of bounds Exception occurred

### ISSUE THREAD

**Issue by Zasilus** [TerraMap/windows#7]
Currently running a large crimson master world. Threw this error:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TerraMap.Data.World.ReadTilesVersion2(BinaryReader reader, Boolean[] importance) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 895
   at TerraMap.Data.World.ReadWorldVersion2(BinaryReader reader) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 459
   at TerraMap.Data.World.Read(String filename) in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 431
   at TerraMap.Data.World.<>c__DisplayClass374_0.<ReadAsync>b__0() in C:\Users\Jason\source\terramap\windows\Data\World.cs:line 393
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__24.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 287
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<Open>d__23.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TerraMap.MainWindow.<OnOpenWorldFile>d__56.MoveNext() in C:\Users\Jason\source\terramap\windows\TerraMap\MainWindow.xaml.cs:line 1189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jasoncoon** [comment]
Try the latest version, just released this morning?  https://terramap.github.io/windows.html

**Comment by Zasilus** [comment]
This was done on the 1.4.1 release

**Comment by jasoncoon** [comment]
Looking now. Unable to reproduce the error. Don't suppose you can attach your world file? It's been opened in Terraria v1.4, right?

**Comment by Zasilus** [comment]
[The_Sector_of_Memes.zip](https://github.com/TerraMap/windows/files/4640596/The_Sector_of_Memes.zip)

**Comment by Zasilus** [comment]
Its a multiplayer world if that changes anything

**Comment by jasoncoon** [comment]
Thanks!  Should be fixed in 1.4.2 now: https://github.com/TerraMap/windows/releases/tag/1.4.2

**Comment by Zasilus** [comment]
It worked thanks
